---
# tasks/main.yml for Ubuntu

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - patch

- name: Upgrade all packages to the latest version on Ubuntu
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  tags:
    - patch

- name: Gather package facts for system
  ansible.builtin.package_facts:

- name: Reboot the system if necessary (after package upgrade)
  ansible.builtin.reboot:
    reboot_timeout: 600
    test_command: uptime
  when: ansible_facts['pkg_mgr'] == 'apt'
  tags:
    - reboot

